# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccb10c123168eacfe2c33c978735be03a88e2691dbf3c7ce69826691e1a8fc2b0de04551ca8002a6126d33461ad744ebd7e5ab14c290b771f8c762123a232fc6

test:
  secret_key_base: 339b5f67a4b25470143d9823467777fac24ea4be92cbf37eaceb0ca37162b524685fe3b97f6c4b094ee3f36bde797224f068256be432632b4aeb571b1b4bb072

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
